import { relativePos } from "../tetris_modules/collision";

// describe("relative position", () => {
// 	it("should edit the ", relativePos);
// });

// describe("newGameBoard", () => {
// 	it("should generate new game board at specified size", () => {
// 		expect(newGameBoard(10)(20)).toStrictEqual([
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			],
// 			[
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY,
// 				CELL.EMPTY
// 			]
// 		]);
// 	});
// });
